---

- name: install prerequisites
  apt: name="{{ item }}" state=latest
  with_items:
    - build-essential
    - libavahi-compat-libdnssd-dev
    - nodejs
  tags: [homebridge, install]

- name: install homebridge
  npm: name=homebridge global=yes state=latest
  notify: reload homebridge
  register: install_homebridge
  tags: [homebridge, install]

- name: install homebridge plugins
  npm: name="homebridge-{{ item }}" global=yes state=latest
  with_items:
  - "{{ homebridge_plugins }}"
  notify: reload homebridge
  tags: [homebridge, install]

- name: create homebridge user
  user: name=homebridge comment=Homebridge system=yes home={{ homebridge_home_dir }}
  tags: [homebridge, install]

- name: create config directory
  file: path={{ homebridge_home_dir }}/.homebridge state=directory owner=homebridge group=homebridge
  notify: reload homebridge
  tags: [homebridge, config]

- name: generate config file
  template: src=config.json.j2 dest={{ homebridge_home_dir }}/config.json owner=homebridge group=homebridge
  notify: reload homebridge
  tags: [homebridge, config]

- name: install service
  copy: src=homebridge.service dest=/lib/systemd/system/ owner=root group=root mode=0644
  notify: reload homebridge
  register: service
  tags: [homebridge, install]

- name: activate service
  service: name=homebridge enabled=yes
  when: service.changed
  tags: [homebridge, install]
